//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadowsocks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shadowsocks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abp_js {
            get {
                object obj = ResourceManager.GetObject("abp_js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # translation for English	
        ///
        ///Main.Shadowsocks=Shadowsocks	
        ///	
        ///# Menu items	
        ///	
        ///Menu.EnableSystemProxy=Enable System Proxy
        ///Menu.Mode=Mode
        ///Menu.PAC=PAC
        ///Menu.Global=Global
        ///Menu.Servers=Servers
        ///Menu.EditServers2=Edit Servers...
        ///Menu.StartOnBoot=Start on Boot
        ///Menu.AllowClientsFromLAN=Allow Clients from LAN
        ///Menu.LocalPAC=Local PAC
        ///Menu.OnlinePAC=Online PAC
        ///Menu.EditLocalPACFile=Edit Local PAC File...
        ///Menu.UpdatePACFromGFWList=Update Local PAC from GFWList
        ///Menu.EditUserRuleForGFWList=Edit User Rule  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] libsscrypto_dll {
            get {
                object obj = ResourceManager.GetObject("libsscrypto_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proxyAddress = &quot;__POLIPO_BIND_IP__&quot;
        ///proxyPort = 8123
        ///
        ///socksParentProxy = &quot;127.0.0.1:__SOCKS_PORT__&quot;
        ///socksProxyType = socks5
        ///diskCacheRoot = &quot;&quot;
        ///localDocumentRoot = &quot;&quot;
        ///
        ///allowedPorts = 1-65535
        ///tunnelAllowedPorts = 1-65535.
        /// </summary>
        internal static string polipo_config {
            get {
                return ResourceManager.GetString("polipo_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] polipo_exe {
            get {
                object obj = ResourceManager.GetObject("polipo_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] proxy_pac_txt {
            get {
                object obj = ResourceManager.GetObject("proxy_pac_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ss16 {
            get {
                object obj = ResourceManager.GetObject("ss16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ss20 {
            get {
                object obj = ResourceManager.GetObject("ss20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ss24 {
            get {
                object obj = ResourceManager.GetObject("ss24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssw128 {
            get {
                object obj = ResourceManager.GetObject("ssw128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Put user rules line by line in this file.
        ///! See https://adblockplus.org/en/filter-cheatsheet
        ///.
        /// </summary>
        internal static string user_rule {
            get {
                return ResourceManager.GetString("user_rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # translation for Simplified Chinese
        ///
        ///Main.Shadowsocks=Shadowsocks
        ///
        ///# Menu items
        ///
        ///Menu.EnableSystemProxy=启用系统代理
        ///Menu.Mode=系统代理模式
        ///Menu.PAC=PAC 模式
        ///Menu.Global=全局模式
        ///Menu.Servers=服务器
        ///Menu.EditServers2=编辑服务器...
        ///Menu.StartOnBoot=开机启动
        ///Menu.AllowClientsFromLAN=允许来自局域网的连接
        ///Menu.LocalPAC=使用本地 PAC
        ///Menu.OnlinePAC=使用在线 PAC
        ///Menu.EditLocalPACFile=编辑本地 PAC 文件...
        ///Menu.UpdatePACFromGFWList=从 GFWList 更新本地 PAC
        ///Menu.EditUserRuleForGFWList=编辑 GFWList 的用户规则...
        ///Menu.ShowQRCode=显示二维码...
        ///Menu.ScanQRCodeFromScreen= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zh_cn {
            get {
                return ResourceManager.GetString("zh_cn", resourceCulture);
            }
        }
    }
}
