//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadowsocks.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shadowsocks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 /* eslint-disable */
        ///// Was generated by gfwlist2pac in precise mode
        ///// https://github.com/clowwindy/gfwlist2pac
        ///
        ///// 2019-10-06: More &apos;javascript&apos; way to interaction with main program
        ///// 2019-02-08: Updated to support shadowsocks-windows user rules.
        ///
        ///var proxy = __PROXY__;
        ///var userrules = __USERRULES__;
        ///var rules = __RULES__;
        ///
        ////*
        ///* This file is part of Adblock Plus &lt;http://adblockplus.org/&gt;,
        ///* Copyright (C) 2006-2014 Eyeo GmbH
        ///*
        ///* Adblock Plus is free software: you can redistribute it and/or  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string abp_js {
            get {
                return ResourceManager.GetString("abp_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 var __USERRULES__ = [];
        ///var __RULES__ = [
        ///    &quot;|http://85.17.73.31/&quot;,
        ///    &quot;||agnesb.fr&quot;,
        ///    &quot;||akiba-web.com&quot;,
        ///    &quot;||altrec.com&quot;,
        ///    &quot;||angela-merkel.de&quot;,
        ///    &quot;||angola.org&quot;,
        ///    &quot;||apartmentratings.com&quot;,
        ///    &quot;||apartments.com&quot;,
        ///    &quot;||arena.taipei&quot;,
        ///    &quot;||asianspiss.com&quot;,
        ///    &quot;||assimp.org&quot;,
        ///    &quot;||athenaeizou.com&quot;,
        ///    &quot;||azubu.tv&quot;,
        ///    &quot;||bankmobilevibe.com&quot;,
        ///    &quot;||banorte.com&quot;,
        ///    &quot;||bash-hackers.org&quot;,
        ///    &quot;||beeg.com&quot;,
        ///    &quot;||global.bing.com&quot;,
        ///    &quot;||bloombergview.com&quot;,
        ///    &quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string default_abp_rule {
            get {
                return ResourceManager.GetString("default_abp_rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # translation for Japanese
        ///
        ///Shadowsocks=Shadowsocks
        ///
        ///# Menu items
        ///
        ///System Proxy=システムプロキシ
        ///Disable=無効
        ///PAC=PAC
        ///Global=全般
        ///Servers=サーバー
        ///Edit Servers...=サーバーの編集...
        ///Statistics Config...=統計情報の設定...
        ///Start on Boot=システムと同時に起動
        ///Forward Proxy...=フォワードプロキシの設定...
        ///Allow other Devices to connect=他のデバイスからの接続を許可する
        ///Local PAC=ローカル PAC
        ///Online PAC=オンライン PAC
        ///Edit Local PAC File...=ローカル PAC ファイルの編集...
        ///Update Local PAC from GFWList=GFWList からローカル PAC を更新
        ///Edit User Rule for GFWList...=ユーザールールの編集...
        ///Secure Local PA [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ja {
            get {
                return ResourceManager.GetString("ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] libsscrypto_dll {
            get {
                object obj = ResourceManager.GetObject("libsscrypto_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 listen-address __PRIVOXY_BIND_IP__:__PRIVOXY_BIND_PORT__
        ///toggle 0
        ///logfile ss_privoxy.log
        ///show-on-task-bar 0
        ///activity-animation 0
        ///forward-socks5 / __SOCKS_HOST__:__SOCKS_PORT__ .
        ///max-client-connections 2048
        ///hide-console
        /// 的本地化字符串。
        /// </summary>
        internal static string privoxy_conf {
            get {
                return ResourceManager.GetString("privoxy_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] privoxy_exe {
            get {
                object obj = ResourceManager.GetObject("privoxy_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ss32Fill {
            get {
                object obj = ResourceManager.GetObject("ss32Fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ss32In {
            get {
                object obj = ResourceManager.GetObject("ss32In", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ss32Out {
            get {
                object obj = ResourceManager.GetObject("ss32Out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ss32Outline {
            get {
                object obj = ResourceManager.GetObject("ss32Outline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ssw128 {
            get {
                object obj = ResourceManager.GetObject("ssw128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] sysproxy_exe {
            get {
                object obj = ResourceManager.GetObject("sysproxy_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] sysproxy64_exe {
            get {
                object obj = ResourceManager.GetObject("sysproxy64_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 ! Put user rules line by line in this file.
        ///! See https://adblockplus.org/en/filter-cheatsheet
        /// 的本地化字符串。
        /// </summary>
        internal static string user_rule {
            get {
                return ResourceManager.GetString("user_rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # translation for Simplified Chinese
        ///
        ///Shadowsocks=Shadowsocks
        ///
        ///# Menu items
        ///
        ///System Proxy=系统代理
        ///Disable=禁用
        ///PAC=PAC 模式
        ///Global=全局模式
        ///Servers=服务器
        ///Edit Servers...=编辑服务器...
        ///Statistics Config...=统计配置...
        ///Start on Boot=开机启动
        ///Forward Proxy...=正向代理设置...
        ///Allow other Devices to connect=允许其他设备连入
        ///Local PAC=使用本地 PAC
        ///Online PAC=使用在线 PAC
        ///Edit Local PAC File...=编辑本地 PAC 文件...
        ///Update Local PAC from GFWList=从 GFWList 更新本地 PAC
        ///Edit User Rule for GFWList...=编辑 GFWList 的用户规则...
        ///Secure Local PAC=保护本地 PAC
        ///Copy Lo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string zh_CN {
            get {
                return ResourceManager.GetString("zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # translation for Traditional Chinese
        ///
        ///Shadowsocks=Shadowsocks
        ///
        ///# Menu items
        ///
        ///System Proxy=系統代理
        ///Disable=禁用
        ///PAC=PAC 模式
        ///Global=全局模式
        ///Servers=伺服器
        ///Edit Servers...=編輯伺服器...
        ///Statistics Config...=統計設定檔...
        ///Start on Boot=開機啟動
        ///Forward Proxy...=正向 Proxy 設定...
        ///Allow other Devices to connect=允許其他裝置連入
        ///Local PAC=使用本機 PAC
        ///Online PAC=使用線上 PAC
        ///Edit Local PAC File...=編輯本機 PAC 檔案...
        ///Update Local PAC from GFWList=從 GFWList 更新本機 PAC
        ///Edit User Rule for GFWList...=編輯 GFWList 的使用者規則...
        ///Secure Local PAC=安全本機 PAC        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string zh_TW {
            get {
                return ResourceManager.GetString("zh_TW", resourceCulture);
            }
        }
    }
}
