//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadowsocks {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shadowsocks.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 /* eslint-disable */
        ///// Was generated by gfwlist2pac in precise mode
        ///// https://github.com/clowwindy/gfwlist2pac
        ///
        ///// 2019-10-06: More &apos;javascript&apos; way to interaction with main program
        ///// 2019-02-08: Updated to support shadowsocks-windows user rules.
        ///
        ///var proxy = __PROXY__;
        ///var userrules = [];
        ///var rules = [];
        ///
        ///// convert to abp grammar
        ///for (var i = 0; i &lt; __RULES__.length; i++) {
        ///    var s = __RULES__[i];
        ///    if (s.substring(0, 2) == &quot;||&quot;) s += &quot;^&quot;;
        ///    rules.push(s);
        ///}
        ///
        ///for (var i = 0; i &lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ABP_JS {
            get {
                return ResourceManager.GetString("ABP_JS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DLC_DAT {
            get {
                object obj = ResourceManager.GetObject("DLC_DAT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!-- Warning: Configuration may reset after shadowsocks upgrade. --&gt;
        ///&lt;!-- If you messed it up, delete this file and Shadowsocks will create a new one. --&gt;
        ///&lt;nlog xmlns=&quot;http://www.nlog-project.org/schemas/NLog.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;targets&gt;
        ///        &lt;!-- This line is managed by Shadowsocks. Do not modify it unless you know what you are doing.--&gt;
        ///        &lt;target name=&quot;file&quot; xsi:type=&quot;File&quot; fileName=&quot;ss_win_temp\shadowsocks [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string NLOG_CONFIG {
            get {
                return ResourceManager.GetString("NLOG_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 listen-address __PRIVOXY_BIND_IP__:__PRIVOXY_BIND_PORT__
        ///toggle 0
        ///logfile ss_privoxy.log
        ///show-on-task-bar 0
        ///activity-animation 0
        ///forward-socks5 / __SOCKS_HOST__:__SOCKS_PORT__ .
        ///max-client-connections 2048
        ///hide-console
        /// 的本地化字符串。
        /// </summary>
        internal static string PRIVOXY_CONF {
            get {
                return ResourceManager.GetString("PRIVOXY_CONF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] PRIVOXY_EXE {
            get {
                object obj = ResourceManager.GetObject("PRIVOXY_EXE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 ! Put user rules line by line in this file.
        ///! See https://adblockplus.org/en/filter-cheatsheet
        /// 的本地化字符串。
        /// </summary>
        internal static string USER_RULE {
            get {
                return ResourceManager.GetString("USER_RULE", resourceCulture);
            }
        }
    }
}
